//
//To regen, with `protoc`, `protoc-gen-go` and `protoc-gen-go-grpc` on the `PATH`
//(the latter two usually via `$GOPATH/bin`), from this dir run:
//
//protoc --go_out=. --go_opt=paths=source_relative \
//--go-grpc_out=. --go-grpc_opt=paths=source_relative \
//service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinStringsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strings       []string               `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty"`
	Delimiter     string                 `protobuf:"bytes,2,opt,name=delimiter,proto3" json:"delimiter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinStringsRequest) Reset() {
	*x = JoinStringsRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinStringsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinStringsRequest) ProtoMessage() {}

func (x *JoinStringsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinStringsRequest.ProtoReflect.Descriptor instead.
func (*JoinStringsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *JoinStringsRequest) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *JoinStringsRequest) GetDelimiter() string {
	if x != nil {
		return x.Delimiter
	}
	return ""
}

type JoinStringsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Joined        string                 `protobuf:"bytes,1,opt,name=joined,proto3" json:"joined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinStringsResponse) Reset() {
	*x = JoinStringsResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinStringsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinStringsResponse) ProtoMessage() {}

func (x *JoinStringsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinStringsResponse.ProtoReflect.Descriptor instead.
func (*JoinStringsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *JoinStringsResponse) GetJoined() string {
	if x != nil {
		return x.Joined
	}
	return ""
}

type ProvideStringsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint32                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvideStringsRequest) Reset() {
	*x = ProvideStringsRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvideStringsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideStringsRequest) ProtoMessage() {}

func (x *ProvideStringsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideStringsRequest.ProtoReflect.Descriptor instead.
func (*ProvideStringsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProvideStringsRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ProvideStringsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	String_       string                 `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvideStringsResponse) Reset() {
	*x = ProvideStringsResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvideStringsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvideStringsResponse) ProtoMessage() {}

func (x *ProvideStringsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvideStringsResponse.ProtoReflect.Descriptor instead.
func (*ProvideStringsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *ProvideStringsResponse) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

type ReceiveStringsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	String_       string                 `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveStringsRequest) Reset() {
	*x = ReceiveStringsRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveStringsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveStringsRequest) ProtoMessage() {}

func (x *ReceiveStringsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveStringsRequest.ProtoReflect.Descriptor instead.
func (*ReceiveStringsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiveStringsRequest) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

type ReceiveStringsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      []string               `protobuf:"bytes,1,rep,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveStringsResponse) Reset() {
	*x = ReceiveStringsResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveStringsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveStringsResponse) ProtoMessage() {}

func (x *ReceiveStringsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveStringsResponse.ProtoReflect.Descriptor instead.
func (*ReceiveStringsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReceiveStringsResponse) GetReceived() []string {
	if x != nil {
		return x.Received
	}
	return nil
}

type ExchangeStringsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	String_       string                 `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
	WantReturn    bool                   `protobuf:"varint,2,opt,name=want_return,json=wantReturn,proto3" json:"want_return,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeStringsRequest) Reset() {
	*x = ExchangeStringsRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeStringsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeStringsRequest) ProtoMessage() {}

func (x *ExchangeStringsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeStringsRequest.ProtoReflect.Descriptor instead.
func (*ExchangeStringsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ExchangeStringsRequest) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *ExchangeStringsRequest) GetWantReturn() bool {
	if x != nil {
		return x.WantReturn
	}
	return false
}

type ExchangeStringsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      []string               `protobuf:"bytes,1,rep,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeStringsResponse) Reset() {
	*x = ExchangeStringsResponse{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeStringsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeStringsResponse) ProtoMessage() {}

func (x *ExchangeStringsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeStringsResponse.ProtoReflect.Descriptor instead.
func (*ExchangeStringsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *ExchangeStringsResponse) GetReceived() []string {
	if x != nil {
		return x.Received
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x02pb\"L\n" +
	"\x12JoinStringsRequest\x12\x18\n" +
	"\astrings\x18\x01 \x03(\tR\astrings\x12\x1c\n" +
	"\tdelimiter\x18\x02 \x01(\tR\tdelimiter\"-\n" +
	"\x13JoinStringsResponse\x12\x16\n" +
	"\x06joined\x18\x01 \x01(\tR\x06joined\"-\n" +
	"\x15ProvideStringsRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\"0\n" +
	"\x16ProvideStringsResponse\x12\x16\n" +
	"\x06string\x18\x01 \x01(\tR\x06string\"/\n" +
	"\x15ReceiveStringsRequest\x12\x16\n" +
	"\x06string\x18\x01 \x01(\tR\x06string\"4\n" +
	"\x16ReceiveStringsResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x03(\tR\breceived\"Q\n" +
	"\x16ExchangeStringsRequest\x12\x16\n" +
	"\x06string\x18\x01 \x01(\tR\x06string\x12\x1f\n" +
	"\vwant_return\x18\x02 \x01(\bR\n" +
	"wantReturn\"5\n" +
	"\x17ExchangeStringsResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x03(\tR\breceived2\xb5\x02\n" +
	"\rSimpleService\x12>\n" +
	"\vJoinStrings\x12\x16.pb.JoinStringsRequest\x1a\x17.pb.JoinStringsResponse\x12I\n" +
	"\x0eProvideStrings\x12\x19.pb.ProvideStringsRequest\x1a\x1a.pb.ProvideStringsResponse0\x01\x12I\n" +
	"\x0eReceiveStrings\x12\x19.pb.ReceiveStringsRequest\x1a\x1a.pb.ReceiveStringsResponse(\x01\x12N\n" +
	"\x0fExchangeStrings\x12\x1a.pb.ExchangeStringsRequest\x1a\x1b.pb.ExchangeStringsResponse(\x010\x01B-Z+github.com/alexballas/bine/examples/grpc/pbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_service_proto_goTypes = []any{
	(*JoinStringsRequest)(nil),      // 0: pb.JoinStringsRequest
	(*JoinStringsResponse)(nil),     // 1: pb.JoinStringsResponse
	(*ProvideStringsRequest)(nil),   // 2: pb.ProvideStringsRequest
	(*ProvideStringsResponse)(nil),  // 3: pb.ProvideStringsResponse
	(*ReceiveStringsRequest)(nil),   // 4: pb.ReceiveStringsRequest
	(*ReceiveStringsResponse)(nil),  // 5: pb.ReceiveStringsResponse
	(*ExchangeStringsRequest)(nil),  // 6: pb.ExchangeStringsRequest
	(*ExchangeStringsResponse)(nil), // 7: pb.ExchangeStringsResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: pb.SimpleService.JoinStrings:input_type -> pb.JoinStringsRequest
	2, // 1: pb.SimpleService.ProvideStrings:input_type -> pb.ProvideStringsRequest
	4, // 2: pb.SimpleService.ReceiveStrings:input_type -> pb.ReceiveStringsRequest
	6, // 3: pb.SimpleService.ExchangeStrings:input_type -> pb.ExchangeStringsRequest
	1, // 4: pb.SimpleService.JoinStrings:output_type -> pb.JoinStringsResponse
	3, // 5: pb.SimpleService.ProvideStrings:output_type -> pb.ProvideStringsResponse
	5, // 6: pb.SimpleService.ReceiveStrings:output_type -> pb.ReceiveStringsResponse
	7, // 7: pb.SimpleService.ExchangeStrings:output_type -> pb.ExchangeStringsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
