//
//To regen, with `protoc`, `protoc-gen-go` and `protoc-gen-go-grpc` on the `PATH`
//(the latter two usually via `$GOPATH/bin`), from this dir run:
//
//protoc --go_out=. --go_opt=paths=source_relative \
//--go-grpc_out=. --go-grpc_opt=paths=source_relative \
//service.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	SimpleService_JoinStrings_FullMethodName     = "/pb.SimpleService/JoinStrings"
	SimpleService_ProvideStrings_FullMethodName  = "/pb.SimpleService/ProvideStrings"
	SimpleService_ReceiveStrings_FullMethodName  = "/pb.SimpleService/ReceiveStrings"
	SimpleService_ExchangeStrings_FullMethodName = "/pb.SimpleService/ExchangeStrings"
)

// SimpleServiceClient is the client API for SimpleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimpleServiceClient interface {
	JoinStrings(ctx context.Context, in *JoinStringsRequest, opts ...grpc.CallOption) (*JoinStringsResponse, error)
	ProvideStrings(ctx context.Context, in *ProvideStringsRequest, opts ...grpc.CallOption) (SimpleService_ProvideStringsClient, error)
	ReceiveStrings(ctx context.Context, opts ...grpc.CallOption) (SimpleService_ReceiveStringsClient, error)
	ExchangeStrings(ctx context.Context, opts ...grpc.CallOption) (SimpleService_ExchangeStringsClient, error)
}

type simpleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleServiceClient(cc grpc.ClientConnInterface) SimpleServiceClient {
	return &simpleServiceClient{cc}
}

func (c *simpleServiceClient) JoinStrings(ctx context.Context, in *JoinStringsRequest, opts ...grpc.CallOption) (*JoinStringsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinStringsResponse)
	err := c.cc.Invoke(ctx, SimpleService_JoinStrings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simpleServiceClient) ProvideStrings(ctx context.Context, in *ProvideStringsRequest, opts ...grpc.CallOption) (SimpleService_ProvideStringsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SimpleService_ServiceDesc.Streams[0], SimpleService_ProvideStrings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &simpleServiceProvideStringsClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SimpleService_ProvideStringsClient interface {
	Recv() (*ProvideStringsResponse, error)
	grpc.ClientStream
}

type simpleServiceProvideStringsClient struct {
	grpc.ClientStream
}

func (x *simpleServiceProvideStringsClient) Recv() (*ProvideStringsResponse, error) {
	m := new(ProvideStringsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *simpleServiceClient) ReceiveStrings(ctx context.Context, opts ...grpc.CallOption) (SimpleService_ReceiveStringsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SimpleService_ServiceDesc.Streams[1], SimpleService_ReceiveStrings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &simpleServiceReceiveStringsClient{ClientStream: stream}
	return x, nil
}

type SimpleService_ReceiveStringsClient interface {
	Send(*ReceiveStringsRequest) error
	CloseAndRecv() (*ReceiveStringsResponse, error)
	grpc.ClientStream
}

type simpleServiceReceiveStringsClient struct {
	grpc.ClientStream
}

func (x *simpleServiceReceiveStringsClient) Send(m *ReceiveStringsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *simpleServiceReceiveStringsClient) CloseAndRecv() (*ReceiveStringsResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReceiveStringsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *simpleServiceClient) ExchangeStrings(ctx context.Context, opts ...grpc.CallOption) (SimpleService_ExchangeStringsClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SimpleService_ServiceDesc.Streams[2], SimpleService_ExchangeStrings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &simpleServiceExchangeStringsClient{ClientStream: stream}
	return x, nil
}

type SimpleService_ExchangeStringsClient interface {
	Send(*ExchangeStringsRequest) error
	Recv() (*ExchangeStringsResponse, error)
	grpc.ClientStream
}

type simpleServiceExchangeStringsClient struct {
	grpc.ClientStream
}

func (x *simpleServiceExchangeStringsClient) Send(m *ExchangeStringsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *simpleServiceExchangeStringsClient) Recv() (*ExchangeStringsResponse, error) {
	m := new(ExchangeStringsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimpleServiceServer is the server API for SimpleService service.
// All implementations must embed UnimplementedSimpleServiceServer
// for forward compatibility
type SimpleServiceServer interface {
	JoinStrings(context.Context, *JoinStringsRequest) (*JoinStringsResponse, error)
	ProvideStrings(*ProvideStringsRequest, SimpleService_ProvideStringsServer) error
	ReceiveStrings(SimpleService_ReceiveStringsServer) error
	ExchangeStrings(SimpleService_ExchangeStringsServer) error
	mustEmbedUnimplementedSimpleServiceServer()
}

// UnimplementedSimpleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSimpleServiceServer struct {
}

func (UnimplementedSimpleServiceServer) JoinStrings(context.Context, *JoinStringsRequest) (*JoinStringsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinStrings not implemented")
}
func (UnimplementedSimpleServiceServer) ProvideStrings(*ProvideStringsRequest, SimpleService_ProvideStringsServer) error {
	return status.Errorf(codes.Unimplemented, "method ProvideStrings not implemented")
}
func (UnimplementedSimpleServiceServer) ReceiveStrings(SimpleService_ReceiveStringsServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveStrings not implemented")
}
func (UnimplementedSimpleServiceServer) ExchangeStrings(SimpleService_ExchangeStringsServer) error {
	return status.Errorf(codes.Unimplemented, "method ExchangeStrings not implemented")
}
func (UnimplementedSimpleServiceServer) mustEmbedUnimplementedSimpleServiceServer() {}

// UnsafeSimpleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimpleServiceServer will
// result in compilation errors.
type UnsafeSimpleServiceServer interface {
	mustEmbedUnimplementedSimpleServiceServer()
}

func RegisterSimpleServiceServer(s grpc.ServiceRegistrar, srv SimpleServiceServer) {
	s.RegisterService(&SimpleService_ServiceDesc, srv)
}

func _SimpleService_JoinStrings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinStringsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleServiceServer).JoinStrings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimpleService_JoinStrings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleServiceServer).JoinStrings(ctx, req.(*JoinStringsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimpleService_ProvideStrings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProvideStringsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimpleServiceServer).ProvideStrings(m, &simpleServiceProvideStringsServer{ServerStream: stream})
}

type SimpleService_ProvideStringsServer interface {
	Send(*ProvideStringsResponse) error
	grpc.ServerStream
}

type simpleServiceProvideStringsServer struct {
	grpc.ServerStream
}

func (x *simpleServiceProvideStringsServer) Send(m *ProvideStringsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SimpleService_ReceiveStrings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SimpleServiceServer).ReceiveStrings(&simpleServiceReceiveStringsServer{ServerStream: stream})
}

type SimpleService_ReceiveStringsServer interface {
	SendAndClose(*ReceiveStringsResponse) error
	Recv() (*ReceiveStringsRequest, error)
	grpc.ServerStream
}

type simpleServiceReceiveStringsServer struct {
	grpc.ServerStream
}

func (x *simpleServiceReceiveStringsServer) SendAndClose(m *ReceiveStringsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *simpleServiceReceiveStringsServer) Recv() (*ReceiveStringsRequest, error) {
	m := new(ReceiveStringsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SimpleService_ExchangeStrings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SimpleServiceServer).ExchangeStrings(&simpleServiceExchangeStringsServer{ServerStream: stream})
}

type SimpleService_ExchangeStringsServer interface {
	Send(*ExchangeStringsResponse) error
	Recv() (*ExchangeStringsRequest, error)
	grpc.ServerStream
}

type simpleServiceExchangeStringsServer struct {
	grpc.ServerStream
}

func (x *simpleServiceExchangeStringsServer) Send(m *ExchangeStringsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *simpleServiceExchangeStringsServer) Recv() (*ExchangeStringsRequest, error) {
	m := new(ExchangeStringsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SimpleService_ServiceDesc is the grpc.ServiceDesc for SimpleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimpleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SimpleService",
	HandlerType: (*SimpleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinStrings",
			Handler:    _SimpleService_JoinStrings_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProvideStrings",
			Handler:       _SimpleService_ProvideStrings_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReceiveStrings",
			Handler:       _SimpleService_ReceiveStrings_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ExchangeStrings",
			Handler:       _SimpleService_ExchangeStrings_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
